finance_pipeline:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: default
      host: clickhouse
      port: 8123
      user: default
      password: "{{ env_var('CLICKHOUSE_PASSWORD') }}"
      secure: False
